Insert into GAME_PROFILE (PROFILE_ID,PROFILE_NAME) values (1,'BATMAN');
Insert into GAME_PROFILE (PROFILE_ID,PROFILE_NAME) values (2,'Lord Of The Rings');

Insert into GAME_PROFILE_CHARACTER (GAME_PROFILE_CHAR_ID,GAME_PROFILE_CHAR_NAME,PROFILE_ID) values (1,'BATMAN',1);
Insert into GAME_PROFILE_CHARACTER (GAME_PROFILE_CHAR_ID,GAME_PROFILE_CHAR_NAME,PROFILE_ID) values (2,'ROBIN',1);
Insert into GAME_PROFILE_CHARACTER (GAME_PROFILE_CHAR_ID,GAME_PROFILE_CHAR_NAME,PROFILE_ID) values (3,'FRODO',2);
Insert into GAME_PROFILE_CHARACTER (GAME_PROFILE_CHAR_ID,GAME_PROFILE_CHAR_NAME,PROFILE_ID) values (4,'GANDALF',2);
