CREATE TABLE GAME_PROFILE 
(
  PROFILE_ID INTEGER NOT NULL 
, PROFILE_NAME VARCHAR(50) NOT NULL 
, CONSTRAINT GAME_PROFILE_PK PRIMARY KEY 
  (
    PROFILE_ID 
  )
);

CREATE TABLE GAME_PROFILE_CHARACTER 
(	GAME_PROFILE_CHAR_ID INTEGER NOT NULL, 
	GAME_PROFILE_CHAR_NAME VARCHAR(50), 
	PROFILE_ID INTEGER, 
	CONSTRAINT GAME_PROFILE_CHARACTER_PK PRIMARY KEY (GAME_PROFILE_CHAR_ID), 
	CONSTRAINT GAME_PROFILE_CHARACTER_UK1 UNIQUE (GAME_PROFILE_CHAR_ID, GAME_PROFILE_CHAR_NAME), 
	CONSTRAINT GAME_PROFILE_CHARACTER_GA_FK1 FOREIGN KEY (PROFILE_ID)
	  REFERENCES GAME_PROFILE (PROFILE_ID) ON DELETE CASCADE 
);

CREATE TABLE GAME_CONTEXT 
(
  GAME_CONTEXT_ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
                (START WITH 1, INCREMENT BY 1)
, GAME_NAME VARCHAR(50) NOT NULL 
, GAME_START_DATE DATE NOT NULL 
);

ALTER TABLE GAME_CONTEXT
ADD CONSTRAINT GAME_CONTEXT_UK1 UNIQUE 
(
  GAME_CONTEXT_ID 
, GAME_NAME 
);

--ALTER TABLE GAME_CONTEXT
--ADD CONSTRAINT GAME_CONTEXT_GAME_CHARACT_FK1 FOREIGN KEY
--(
--  GAME_CHAR_ID 
--)
--REFERENCES GAME_CHARACTER
--(
--  CHAR_ID 
--);


CREATE TABLE GAME_CHARACTER 
(
  CHAR_ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
                (START WITH 1, INCREMENT BY 1)
, CHAR_NAME VARCHAR(50) 
, EXPERIENCE INTEGER NOT NULL 
, RANK INTEGER 
, GAME_PROFILE_CHAR_ID INTEGER NOT NULL 
, LOCATION INTEGER NOT NULL 
, GAME_CONTEXT_ID INTEGER NOT NULL 
, CHARACTER_TYPE CHAR NOT NULL 
);

ALTER TABLE GAME_CHARACTER
ADD CONSTRAINT GAME_CHARACTER_UK1 UNIQUE 
(
  CHAR_ID 
, CHAR_NAME 
);

ALTER TABLE GAME_CHARACTER
ADD CONSTRAINT GAME_CHARACTER_GAME_PROFI_FK1 FOREIGN KEY
(
  GAME_PROFILE_CHAR_ID 
)
REFERENCES GAME_PROFILE_CHARACTER
(
  GAME_PROFILE_CHAR_ID 
);

ALTER TABLE GAME_CHARACTER
ADD CONSTRAINT GAME_CHARACTER_GAME_CONTE_FK1 FOREIGN KEY
(
  GAME_CONTEXT_ID 
)
REFERENCES GAME_CONTEXT
(
  GAME_CONTEXT_ID 
);

--CREATE SEQUENCE  PRODUCT_ID_SEQ  MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1 ;


